title: Luca Bulfon
description: Master's graduate in Business Analytics with an undergraduate in Computer Science and a minor in Business
Administration. Former NCAA Division 1 soccer player.
Seeking an entry-level position as Data Analyst. Master Degree will allow for a 3 year OPT.
logo: 
theme: jekyll-theme-minimal
